### ISSUE TITLE
Offline deployment

### ISSUE THREAD

**Issue by samuelschuettler** [UMEssen/Body-and-Organ-Analysis#23]
To be able to use it on our gpu cluster the docker containers need to be offline (there is no internet connection available). 
I can download, create and export the containers, but the problem is that the weights for the TotalSegmentator tasks don't download when setting up the containers.

I can try and put some test images like TCIA data through it but it seems like the real images we push to the BOA containers trigger more tasks than get downloaded for TCIA data. Can you provide a list of all the weights one needs to download to the weights folder to have full offline functionality? Or even better a script that downloads everything needed for offline-usage.

Cheers
Samuel from Hamburg

**Comment by giuliabaldini** [comment]
Hey!

I paste here (and [attach](https://github.com/UMEssen/Body-and-Organ-Analysis/files/14521453/download_pretrained_weights.py.zip)) a script that downloads all the weights. You can just clone the repository, install the packages (`poetry install`) and then run this script. Otherwise, you can also install the package from pip (`pip install body-organ-analysis`) and then run this script. In the list, you can select which weights you want to download, but it should be all of them.

```python
import body_organ_analysis
from totalsegmentator.libs import download_pretrained_weights
import logging
import os
from time import sleep

logging.basicConfig()
logging.getLogger().setLevel(logging.INFO)

if __name__ == "__main__":
    # Set up the path for the weights
    os.environ["TOTALSEG_WEIGHTS_PATH"] = "tmp"

    weights_ids = [
        # Weights used by default by the PACS integration (total + bca)
        251,  # Total
        252,  # Total
        253,  # Total
        254,  # Total
        255,  # Total
        542,  # BCA
        273,  # Body
        # Other weights
        258,  # Lung vessels
        150,  # Cerebral bleed
        260,  # Hip implant
        503,  # Coronary arteries
        315,  # Pleural pericardial effusion
        8,  # Hepatic vessels
    ]
    for task_id in weights_ids:
        download_pretrained_weights(task_id)
        sleep(5)
```

Hope this helps!

Best,
Giulia

**Comment by samuelschuettler** [comment]
This has worked. Thank you for the quick support :+1:
